### ISSUE TITLE
Address Range

### ISSUE THREAD

**Issue by fredz2005** [WifWaf/AT24CM01#2]
Hi, thanks for contributing this library.   My HW is an arduino  with SAMD21G + AT24CM01.  I'm able to read and write to the the EEPROM using the standard arduino wire.h API, but it doesn't support the entire address range of the AT24CM01.  I updated my code to use your library.  It works well with EEPROM address ranges between 0x00 and 0xFF.  It doesn't seem to work for me at higher addresses, such as 0xFFFF.  I don't know if this is a bug with my system or an issue with the library.   I'm using your example program 'AllVariables' and just changed the address in read/write byte cmd to 0xFFFF.  No compile errors.  It appears the EEPROM.writeByte(0xFFFF,TEST_BYTE) doesn't actually write to the EEPROM.

**Comment by WifWaf** [comment]
The latest release (from Jan last year) isn't being picked up by the library manager.

If you replace your local library with the code from the master branch, it should fix it.

I'll make a new release to see if it changes anything - otherwise, I'll raise an issue with Arduino.

**Comment by fredz2005** [comment]
I appreciate your quick reply.  I tried the current release and it works all the way to 0x1FFFF.  Thanks.

A question regarding i2c addressing in your library.  I looked through the .h file and see this line:
    #define ATDEVADR 0x50                // Lowest page address
Is this the i2c address?  I have other i2c devices on my board and wanted to make sure I understood how the bus addressing worked so I don't create problems.

Your code is very compact for the amount of functionality you have in the library.   Excellent work.

**Comment by WifWaf** [comment]
I appreciate the positive feedback :).

Yes, however... I believe it uses 0x50 and 0x51 (the memory is in two physical parts - I think that's why).

0x50 assumes pins A1 and A2 are wired to GND (a standard setup), if not, you can change the address in the header and the library will simply take the following address for the other half of memory.

Not sure if that helps?

**Comment by fredz2005** [comment]
I had to look at the addressing section of the data sheet again.  Since A16 is only accessible in the i2c address byte, you toggle A16 by changing the i2c address from 0x50 (0x0XXXX) to 0x51 (0x1XXXX).  The 0x5x must be the required device type ID (0xA).  Did you look at Wire source to figure out how stuffs the lower 4 bits of the i2c address into the control byte?  Thanks again.

**Comment by WifWaf** [comment]
Yes, I did (it was a whle ago now). 

Is the macro in the .cpp what you're looking for? 

If the address is greater than two bytes, it must be the second address (0x51) - it adds the remaining 0x01 to the address.

https://github.com/WifWaf/AT24CM01/blob/72f3f08b758bfe4c1e3d88e49c5ba307ae47b624/src/AT24CM01.cpp#L15

**Comment by fredz2005** [comment]
I completed testing the library with test code and it works fine.   You've got an elegant solution because it covers all 17 address bits, while using the standard Arduino Wire API.   This week I'll add your library to my project code.  I don't anticipate any issues.  Thanks again for your help.

**Comment by WifWaf** [comment]
Thanks and you're welcome - I hope it integrates well. 

If you find any issues or make improvements, feel free to make a pull-request.  :)
