### ISSUE TITLE
Float Values

### ISSUE THREAD

**Issue by fredz2005** [WifWaf/AT24CM01#3]
I was able to incorporate your lib into my pgm and its working as expected.  Thanks.   .writeByte()/.readByte() and .writeFloat()/read.Float() methods write and recover data accurately.  However, when I look at data in the EEPROM using my EEdisplay() function, bytes written using .writeBytes() look as I would expect (HEX ASCII), but locations written using .writeFloat() are not HEX ASCII.   What format does .writeFloat() use to store characters in EEPROM?  (I looked at both your .h and .cpp and couldn't figure out the answer.)

One other question.  You have both .writeFloat() and .writeDouble() methods.  I read the gnu complier for AVR devices treats float and double the same (4bytes).   I'm using an  SAMD21, which uses an ARM compiler.   Is there a functional difference between the two methods?

Thanks for your comments.

**Comment by WifWaf** [comment]
Yes, a Float and Double vary depending on which MCU you're using, so the library uses the sizeof() operator to create compatibility.

I think the SAM21D is an 8-byte Double and 4-byte Float - try printing sizeof(float and sizeof(double) through serial.

In regards to how they're stored: there's a union at the bottom of the header file. Unions use shared memory for all continued components, so if it includes a float and byte - you can simply use the array to pull out that data byte by byte.  I do not know if there is a particular format name for the raw bytes?

Glad you bought the topic up though, I've noticed Ineed to change the array size in the union to sizeof(double) to avoid overflow  👍 .

**Comment by fredz2005** [comment]
Thanks for your comments.  My pgm is working with the library.  I don't see a functional pblm.  I'm still unclear how floats are represented in memory.  Below is dump. At adr 30h are four uint8 written with byteWrite(): 28,2,2,8 displayed as expected.  At adr 10h is the number -3.20 written with writeFloat(). Can't make sense of it.   Again, readFloat() does recover -3.20.  At adr 20h is the number 0.0 written with writeFloat() and readFloat() recovers 0.0.   I use readByte() and Serial.println(value,HEX) to read and display the memory values.  I thought it might be a fixed offset or 1s/2s complement, neither provide an answer.  If you have an insight as to what is occurring, please let me know.
0x00000	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	55	
0x00010	C9	CC	4C	C0	32	30	00	00	00	00	00	00	00	00	00	00	
0x00020	33	33	A3	B3	00	00	00	00	00	00	00	00	00	00	00	00	
0x00030	28	02	02	08	00	00	00	00	00	00	00	00	00	00	00	00

**Comment by WifWaf** [comment]
I'll try to explain what little I know :)

A float is 4 bytes, so from address 0x00010 I can see the HEX is C9 CC 4C C0 , or 0xC9CC4CC0. 

Floats have more complex storage formats which are broken into 4 parts which included a 'sign' (+ or -) 'exponent' (power) and 'mantissa' (decimal part). In addition to this, they also 'endianness' which is the ordering of they are stored with respect to the MSB (most significant byte) and LSB (least significant byte).

Try entering the 4-byte hex for the float here: https://www.scadacore.com/tools/programming-calculators/online-hex-converter/

You can see that the format which roughly returns float (-3.20) is called 'Little Endian (DCBA)'. 'Endian' comes from endianness and 'Little' from LSB while 'DCBA' refers to how the 4 bytes are ordered (where A is the MSB).  Conversely, if the bytes were ordered from MSB then the name given would be 'Big Endian' with a byte order of ABCD.

A better way to understand this is to type in 0xC9CC4CC0 here: https://gregstoll.com/~gregstoll/floattohex/

You can see how the binary is stored and how the properties assigned to each byte are put together to produce the float value (you'll need to tick endianness at the top).

Floats are a bit of an oddity in terms of storage and behavior, but hopefully, this helps?

**Comment by fredz2005** [comment]
I appreciate you taking the time to explain this.   The gregstoll.com calculator is interesting.   Thanks again.
