### ISSUE TITLE
Need multiple device support

### ISSUE THREAD

**Issue by pravinraghul** [WifWaf/AT24CM01#5]
Support for up to four devices, as mentioned in the below datasheet.
http://ww1.microchip.com/downloads/en/DeviceDoc/atmel-8812-seeprom-at24cm01-datasheet.pdf#G1061488

- Required read & write API's for different devices memory address.

**Comment by WifWaf** [comment]
You can find the bit masks In the .cpp and address (7 bit) in the header file. I'm happy to add an additional argument to the constructor however.
